### ISSUE TITLE
Cannot load the CT file

### ISSUE THREAD

**Issue by ZeroOne00001** [plumbwicked/Wicked-Menu#5]
cannot load ct file

Not a valid file

![Capture](https://user-images.githubusercontent.com/86359879/123099773-1e8d9700-d450-11eb-9fe2-516ea6c347e5.PNG)

**Comment by plumbwicked** [comment]
Re download and try again. It should be fixed

**Comment by ZeroOne00001** [comment]
thanks now it worked
