### ISSUE TITLE
STILL getting the issue, 

### ISSUE THREAD

**Issue by hoodwink78** [plumbwicked/Wicked-Menu#6]
[error.pdf](https://github.com/plumbwicked/Wicked-Menu/files/6702971/error.pdf)

**Comment by plumbwicked** [comment]
Fixed redownload and try again .

Josiah Danielson

**Comment by plumbwicked** [comment]
Fixed , re download and try again.

**Comment by hoodwink78** [comment]
yeah some features like god mode and infinite stam and deadeye and teleport and infinite items arent working tho

**Comment by hoodwink78** [comment]
yeah it does, but i think godmode stopped working, let me check once and get back to you
